name: jwt practice server CI/CD


on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

env:
  S3_BUCKET_NAME: final-team2-code-deploy

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean build

# application.properties 파일 생성
    - name: Make application.properties
      run: |
        cd ./src/main/resources
        touch ./application.properties

        echo "${{ secrets.APPLICATION_PROPERTIES }}" >> ./application.properties
      shell: bash

#디렉토리 생성
    - name: Make Directory
      run: mkdir -p deploy

    - name: Copy appspec.yml to deploy
      run: cp appspec.yml ./deploy

    - name: Copy deploy.sh to deploy
      run: cp deploy.sh ./deploy

# Jar파일 복사
    - name: Copy Jar
      run: cp ./build/libs/*.jar ./deploy

    - name: Make zip file
      run: zip -r ./final-team2.zip ./deploy
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./final-team2.zip s3://$S3_BUCKET_NAME/

# Deploy
    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run:
        aws deploy create-deployment
        --application-name final-team2
        --deployment-group-name team2-group
        --file-exists-behavior OVERWRITE
        --s3-location bucket=final-team2-code-deploy,bundleType=zip,key=final-team2.zip
        --region ap-northeast-2
